apps/employee/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'employee'

urlpatterns = [
    path('', login_required(views.EmployeeListView.as_view()),
         name='employee_list'),
    path('signup/', login_required(views.signup), name='signup'),
    path('edit/<int:pk>', login_required(views.edit_employee), name='edit_employee'),
    path('profile/', login_required(views.profile), name='users-profile'),
    path('profile/edit/', login_required(views.edit_profile), name='edit_profile'),

    path('delete/<int:pk>', login_required(views.employee_delete),
         name='employee_delete'),

    # rutas área de trabajo
    path('worker_area', login_required(views.WorkerAreaListView.as_view()),
         name='worker_area_list'),
    path('worker_area/new/', login_required(views.WorkerAreaNew.as_view()),
         name='worker_area_new'),
    path('worker_area/edit/<int:pk>', login_required(views.WorkerAreaEdit.as_view()),
         name='worker_area_edit'),
    path('worker_area/delete/<int:pk>', login_required(views.worker_area_delete),
         name='worker_area_delete'),

    # rutas turnos de trabajo
    path('work_shift', login_required(views.WorkShiftListView.as_view()),
         name='work_shift_list'),
    path('work_shift/new/', login_required(views.WorkShiftNew.as_view()),
         name='work_shift_new'),
    path('work_shift/edit/<int:pk>', login_required(views.WorkShiftEdit.as_view()),
         name='work_shift_edit'),
    path('work_shift/delete/<int:pk>', login_required(views.work_shift_delete),
         name='work_shift_delete'),

    # ruta análisis de emociones
    path('video_list', login_required(views.VideoListView.as_view()),
         name='video_list'),
    path('video/new/', login_required(views.VideoNew.as_view()),
         name='video_new'),
    path('video/edit/<int:pk>', login_required(views.VideoEdit.as_view()),
         name='video_edit'),
    path('video/delete/<int:pk>', login_required(views.video_delete),
         name='video_delete'),

    path('analyze_video', login_required(views.analyze_video),
         name='analyze_video'),
    path('analyze_video/task-status/<str:task_id>/', 
         views.analyze_video_task_status, name='analyze_video-task_status'),

    # rutas Analytics
    path('analytics', login_required(views.analytics), name='analytics'),

    path('get_worker_area_emotions/', login_required(views.get_worker_area_emotions),
         name='get_worker_area_emotions'),
    path('get_work_shift_emotions/', login_required(views.get_work_shift_emotions),
         name='get_work_shift_emotions'),
    path('get_hourly_emotions/', login_required(views.get_hourly_emotions),
         name='get_hourly_emotions'),
    path('get_employee_hourly_emotions/', login_required(views.get_employee_hourly_emotions),
         name='get_employee_hourly_emotions'),

    # rutas charts
    path('charts', login_required(views.charts), name='charts'),
    path('get_worker_area_chart_data/', 
         login_required(views.get_worker_area_chart_data),
         name='get_worker_area_chart_data'),
    path('get_work_shift_chart_data/', 
         login_required(views.get_work_shift_chart_data),
         name='get_work_shift_chart_data'),
    path('get_hour_chart_data/', 
         login_required(views.get_hour_chart_data),
         name='get_hour_chart_data'),
    path('get_employee_chart_data/', 
         login_required(views.get_employee_chart_data),
         name='get_employee_chart_data'),

    # rutas del usuario normal
    path('me', login_required(views.MeListView.as_view()), name="me"),
    path('me/video/new/', login_required(views.MeVideoNew.as_view()),
         name='me_video_new'),
]

welltrack_ia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    # app
    path('', include('apps.home.urls')),
    path('employee/', include('apps.employee.urls', namespace='employee')),
    path('api/', include('apps.api.urls', namespace='api')),

    # 3rd party

]

# Serve static assets in dev
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/head.html
{% load static %}

<meta charset="UTF-8" />
<meta name="app-name" content="{{ _("WellTrack IA") }}">
<meta name="copyright" content="© 2024 WellTrack IA">
<meta name="description" content="Algoritmos, InsightFace, Employee, Emotion analysis">
<meta name="keywords" content="HTML, JavaScript, Django, Bootstrap, MDB, Notiflix">
<meta name="author" content="Javier Gracia M & Washington Andrade">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />

<!-- favicon  -->
<link rel="shortcut icon" href="{% static 'img/icon/fav.svg' %}" type="image/x-icon">

<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" />

<!-- Google Fonts Roboto -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />

<!-- MDB -->
<link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />

<!-- Notiflix -->
<link rel="stylesheet" href="{% static 'vendor/notiflix/dist/notiflix-3.2.7.min.css' %}" />

<!-- Custom styles -->
<link rel="stylesheet" href="{% static 'css/admin.css' %}" />

<!-- DataTables -->
<link rel="stylesheet" href="{% static 'vendor/DataTables/datatables.css' %}">

templates/includes/modals.html
<!-- Logout Modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <form id="logout-form" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <div class="modal-content">
        <div class="modal-header bg-primary text-white">
          <h5 class="modal-title" id="logoutModalLabel">{{ _("Logout") }}</h5>
          <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="lead">
            {{ _("Are you sure you want to logout?") }}
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">
            {{ _("Cancel") }}
          </button>
          <button type="submit" class="btn btn-primary" onclick="window.location.href='{% url 'logout' %}'">{{ _("Logout") }}</button>
        </div>
      </div>
    </form>
  </div>
</div>


{# Renderiza Formulario Modal #}
<div class="modal fade" id="popup" tabindex="-1" role="dialog" aria-labelledby="popupModalLabel"></div>

templates/includes/nav first.html
{% load static %}

<!-- Navbar -->
<nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-collapse-init data-mdb-target="#sidebarMenu"
      aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Brand -->
    <a class="navbar-brand" href="#">
      <!--<img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png" height="25" alt="" loading="lazy" />-->
      <img src="{% static 'img/logo/welltrack-transaprent-noshadows.png' %}" height="25" alt="" loading="lazy" />
    </a>
    <!-- Search form -->
    <form class="d-none d-md-flex input-group w-auto my-auto">
      <input autocomplete="off" type="search" class="form-control rounded"
        placeholder="{{ _('Search') }}" style="min-width: 225px" />
      <span class="input-group-text border-0"><i class="fas fa-search"></i></span>
    </form>

    <!-- Right links -->
    <ul class="navbar-nav ms-auto d-flex flex-row">
      <!-- Notification dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow" href="#" id="navbarDropdownMenuLink"
          role="button" data-mdb-dropdown-init aria-expanded="false">
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger">1</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="#">Some news</a></li>
          <li><a class="dropdown-item" href="#">Another news</a></li>
          <li>
            <a class="dropdown-item" href="#">Something else</a>
          </li>
        </ul>
      </li>

      <!-- Icon -->
      <li class="nav-item">
        <a class="nav-link me-3 me-lg-0" href="#">
          <i class="fas fa-fill-drip"></i>
        </a>
      </li>
      <!-- Icon -->
      <li class="nav-item me-3 me-lg-0">
        <a class="nav-link" href="#">
          <i class="fab fa-github"></i>
        </a>
      </li>

      <!-- Icon dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow" href="#" id="navbarDropdown" role="button"
          data-mdb-dropdown-init aria-expanded="false">
          <i class="fa-solid fa-flag-usa m-0"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <li>
            <a class="dropdown-item" href="#"><i class="fa-solid fa-flag-usa"></i>English
              <i class="fa fa-check text-success ms-2"></i></a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>
          <li>
            <a class="dropdown-item" href="#"><i class="poland flag"></i>Polski</a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><i class="china flag"></i>中文</a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><i class="japan flag"></i>日本語</a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><i class="germany flag"></i>Deutsch</a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><i class="france flag"></i>Français</a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><i class="spain flag"></i>Español</a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><i class="russia flag"></i>Русский</a>
          </li>
          <li>
            <a class="dropdown-item" href="#"><i class="portugal flag"></i>Português</a>
          </li>
        </ul>
      </li>

      <!-- Avatar -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" href="#"
          id="navbarDropdownMenuLink" role="button" data-mdb-dropdown-init aria-expanded="false">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img (31).jpg" class="rounded-circle" height="22"
            alt="" loading="lazy" />
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="#">My profile</a></li>
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li>
            <a class="dropdown-item" href="#" data-mdb-modal-init data-mdb-target="#logoutModal">
              <i class="fas fa-sign-out-alt me-2"></i>{{ _("Logout") }}
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

templates/includes/nav.html
{% load static %}

<!-- Navbar -->
<nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <!-- Container wrapper -->
  <div class="container-fluid justify-content-between">
    <!-- Left elements -->
    <div class="d-flex">
      <!-- Toggle button -->
      <button class="navbar-toggler" type="button" data-mdb-collapse-init data-mdb-target="#sidebarMenu"
        aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Brand -->
      <a class="navbar-brand" href="#">
        <!--<img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png" height="25" alt="" loading="lazy" />-->
        <img src="{% static 'img/logo/welltrack-transaprent-noshadows.png' %}" height="25" alt="" loading="lazy" />
      </a>
    </div>
    <!-- Left elements -->

    <!-- Center elements -->
    
    <ul class="navbar-nav flex-row d-none d-md-flex">
      {% if user.is_authenticated and user.is_staff %}
      <li class="nav-item me-3 me-lg-1 active">
        <a class="nav-link" href="{% url 'index' %}">
          <span><i class="fas fa-tachometer-alt fa-lg me-1"></i>{{ _("Dashboard") }}</span>
        </a>
      </li>

      <li class="nav-item me-3 me-lg-1">
        <a class="nav-link" href="{% url 'employee:video_list' %}">
          <span><i class="fas fa-clapperboard fa-lg me-1"></i>{{ _("Uploaded videos") }}</span>
        </a>
      </li>
      {% else %}
      <li class="nav-item me-3 me-lg-1">
        <a class="nav-link" href="{% url 'employee:me' %}">
          <span><i class="fas fa-clapperboard fa-lg me-1"></i>{{ _("Uploaded videos") }}</span>
        </a>
      </li>
      {% endif %}
    </ul>
    <!-- Center elements -->

    <!-- Right links -->
    <ul class="navbar-nav flex-row">

      <li class="nav-item me-3 me-lg-0">
        <a class="nav-link" href="https://github.com/jgracia/welltrack_ia.git">
          <i class="fab fa-github"></i>
        </a>
      </li>

      <!-- Icon dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow" href="#" id="navbarDropdown" role="button"
          data-mdb-dropdown-init aria-expanded="false">
          <img src="{% static 'img/icon/ic_flag_en.svg' %}" style="width: 20px; height: auto;">
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <li>
            <a class="dropdown-item" href="#">
              <img src="{% static 'img/icon/ic_flag_en.svg' %}" alt="USA Flag" class="me-2" 
                style="width: 20px; height: auto;">English
                  <i class="fa fa-check text-success ms-2"></i>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>
          <li>
            <a class="dropdown-item" href="#">
              <img src="{% static 'img/icon/ic_flag_es.svg' %}" alt="Spain Flag" class="me-2" 
                style="width: 20px; height: auto;">Español
            </a>
          </li>
        </ul>
      </li>

      <!-- Avatar -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" href="#"
          id="navbarDropdownMenuLink" role="button" data-mdb-dropdown-init aria-expanded="false">
          <img src="{{ user.profile.image_url }}" class="rounded-circle" height="22"
            alt="" loading="lazy" />
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="#">{{ _('My profile') }}</a></li>
          <!--<li><a class="dropdown-item" href="#">Settings</a></li>-->
          <li>
            <a class="dropdown-item" href="#" data-mdb-modal-init data-mdb-target="#logoutModal">
              <i class="fas fa-sign-out-alt me-2"></i>{{ _("Logout") }}
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

templates/includes/scripts.html
{% load static %}

<!-- MDB -->
<script type="text/javascript" src="{% static 'js/mdb.umd.min.js' %}"></script>

<!-- Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>


<!-- Notiflix -->
<script type="text/javascript" src="{% static 'vendor/notiflix/dist/notiflix-3.2.7.min.js' %}"></script>

<!-- Custom scripts -->
<script type="text/javascript" src="{% static 'js/app.js' %}"></script>

<!-- DataTables -->
<script src="{% static 'vendor/DataTables/datatables.js' %}"></script>

templates/includes/sidebar.html
<!-- Sidebar -->
<nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
  <div class="position-sticky">
    <div class="list-group list-group-flush mx-3 mt-4">
      {% if user.is_authenticated and user.is_staff %}
      <a href="{% url 'index' %}" class="list-group-item list-group-item-action py-2 {% if 'index' in segment %} active {% endif %}" data-mdb-ripple-init aria-current="true">
        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>{{ _("Dashboard") }}</span>
      </a>
      <a href="{% url 'employee:analytics' %}" class="list-group-item list-group-item-action py-2 {% if 'analytics' in segment %} active {% endif %}" data-mdb-ripple-init>
        <i class="fas fa-chart-line fa-fw me-3"></i><span>{{ _("Analytic Data") }}</span></a>
      <a href="{% url 'employee:charts' %}" class="list-group-item list-group-item-action py-2 {% if 'charts' in segment %} active {% endif %}" data-mdb-ripple-init>
        <i class="fas fa-chart-bar fa-fw me-3"></i><span>{{ _("Charts") }}</span></a>

      <a href="{% url 'employee:video_list' %}" class="list-group-item list-group-item-action py-2 {% if 'emotion-video' in segment %} active {% endif %}" data-mdb-ripple-init>
        <i class="fas fa-clapperboard fa-fw me-3"></i><span>{{ _("Uploaded videos") }}</span>
      </a>
      <a href="{% url 'employee:employee_list' %}" class="list-group-item list-group-item-action py-2 {% if 'employee' in segment %} active {% endif %}" data-mdb-ripple-init><i
          class="fas fa-users fa-fw me-3"></i><span>{{ _("Employees") }}</span></a>
      <a href="{% url 'employee:worker_area_list' %}" class="list-group-item list-group-item-action py-2 {% if 'worker-area' in segment %} active {% endif %}" data-mdb-ripple-init><i
          class="fas fa-diagram-project fa-fw me-3"></i><span>{{ _("Worker Area") }}</span></a>
      <a href="{% url 'employee:work_shift_list' %}" class="list-group-item list-group-item-action py-2 {% if 'work-shift' in segment %} active {% endif %}" data-mdb-ripple-init>
        <i class="fas fa-clock fa-fw me-3"></i><span>{{ _("Work Shift") }}</span>
      </a>
      {% else %}
      <a href="{% url 'employee:me' %}" class="list-group-item list-group-item-action py-2 {% if 'me' in segment %} active {% endif %}" data-mdb-ripple-init>
        <i class="fas fa-clapperboard fa-fw me-3"></i><span>{{ _("Uploaded videos") }}</span>
      </a>
      {% endif %}
    </div>
  </div>
</nav>
<!-- Sidebar -->